/**
 * Battle Music Playlist - The Shattered Dominion
 * Add new tracks here. The player will pick them up automatically.
 *
 * Lyrics are plain string arrays - the player rolls through them
 * evenly across the song duration. No timestamps needed.
 */

import ashesRememberSrc from "./ashes-remember.mp3";
import everyKingdomSrc from "./every-kingdom-believes.mp3";
import theHonestDarkSrc from "./the-honest-dark.mp3";
import theDawnSrc from "./the-dawn-was-ours-to-give.mp3";
import theGroundSrc from "./the-ground-remembers.mp3";
import iBurnedFirstSrc from "./i-burned-first.mp3";

export interface Track {
  id: string;
  title: string;
  artist: string;
  src: string;
  lyrics: string[];
}

// ============================================================================
//  TRACK 1 - Ashes Remember (Main Anthem)
// ============================================================================
const ASHES_REMEMBER_LYRICS: string[] = [
  "Ash to ash, throne to throne",
  "The light that fell still lights the bone",
  "",
  "We were born beneath a shattered sky",
  "Where the old gods bled and the new ones lie",
  "Every kingdom carved from a single wound",
  "Every flag we raise is a stolen rune",
  "",
  "And the fire knows your name",
  "And the earth will stake its claim",
  "And the shadow trades in blame",
  "But nothing dies the same",
  "",
  "Ashes remember what the living forget",
  "Every war we wage is the first one yet",
  "Lay your cards where the broken gods wept",
  "Ashes remember - ashes remember",
  "",
  "Light will promise what it cannot keep",
  "Shadow sells you secrets in your sleep",
  "Fire will love you till there's nothing left",
  "Earth will hold you down until your death",
  "",
  "And the throne has no king",
  "And the sword has no swing",
  "And the prayer has no wing",
  "But we play - we play - we play",
  "",
  "Ashes remember what the living forget",
  "Every war we wage is the first one yet",
  "Lay your cards where the broken gods wept",
  "Ashes remember - ashes remember",
  "",
  "I had a name before the Shattering",
  "I had a home before the scattering",
  "Now I'm just a card in someone's hand",
  "Played and spent across a burning land",
  "",
  "Ashes remember what the living forget",
  "Every war we wage is the first one yet",
  "Lay your cards where the broken gods wept",
  "Ashes remember - ashes remember",
  "",
  "Ash to ash... throne to throne...",
  "We play the game... to find our way home.",
];

// ============================================================================
//  TRACK 2 - Every Kingdom Believes (Unlockable)
// ============================================================================
const EVERY_KINGDOM_LYRICS: string[] = [
  "I learned the truth the night they came",
  "With holy light and righteous flame",
  "They burned my mother's hands for stealing bread",
  "And sang a hymn while she bled",
  "",
  "So do not speak to me of mercy",
  "Mercy is a word the fed",
  "Teach to the hungry",
  "",
  "I know what kindness looks like",
  "From the underneath",
  "",
  "I held a dying soldier - not mine, theirs",
  "Shadow blade still wet inside his chest",
  "He whispered \"tell them I was brave\"",
  "I lied and said the light would let him rest",
  "",
  "What else do you want from me",
  "I know the prayer is empty",
  "I say it anyway",
  "Because the boy was seventeen",
  "And someone had to say",
  "That it mattered",
  "That he was here",
  "That any of us were here at all",
  "",
  "They call me destroyer",
  "Like I chose the burning",
  "Like I wasn't the first thing the flame consumed",
  "",
  "I loved a garden once",
  "I loved a house with a door that didn't lock",
  "Because we trusted the road",
  "Then the road brought soldiers",
  "Wearing Light",
  "Wearing Earth",
  "Wearing reasons",
  "",
  "I didn't learn to burn",
  "I learned that nothing you love",
  "Is safe from someone else's",
  "Belief",
  "That they deserve it more",
  "",
  "They tell me I am stubborn",
  "That I hold too tightly to the dirt",
  "But you have never buried a child",
  "In soil you raised them from",
  "And been told that the ground",
  "Belongs to someone else now",
  "Because their god said so",
  "",
  "I do not hate the fire",
  "I do not hate the shadow",
  "I hate that they believe",
  "As deeply as I do",
  "And only one of us can be right",
  "",
  "...can we",
  "",
  "What if your light is my darkness wearing white",
  "What if my mercy is just fear that learned a name",
  "What if I burned the only thing that could have saved us",
  "What if the ground I'm standing on is someone's grave",
  "",
  "We made the war because we loved something",
  "Every single one of us",
  "Loved something so deeply",
  "That we could not bear the world",
  "Where it was not the only truth",
  "",
  "And so we burned each other's truths",
  "And called it justice",
  "And called it survival",
  "And called it necessary",
  "And called it holy",
  "",
  "And the children learned the songs",
  "And the children raised the flags",
  "And the children",
  "Grew into us",
  "",
  "Every kingdom believes it is the kingdom that was wronged.",
];

// ============================================================================
//  TRACK 3 - The Honest Dark (Shadow's Anthem)
// ============================================================================
const HONEST_DARK_LYRICS: string[] = [
  "You built your thrones on pretty words",
  "And made the poor applaud",
  "You wrote the laws in golden ink",
  'And signed them "will of God"',
  "",
  "I watched",
  "I waited",
  "I took notes",
  "",
  "You think the dark is where the monsters live",
  "You're right",
  "But you made us",
  "Every single one of you made us",
  "",
  "With your clean hands and your closed doors",
  "And the jobs you needed done",
  "But couldn't name out loud",
  "",
  "We are the invoice you never paid",
  "We are the hand you shook at midnight",
  "And denied at dawn",
  "",
  "So call me thief",
  "Call me liar",
  "Call me the shadow on your holy wall",
  "",
  "But I have never killed a man",
  "And told his children it was justice",
  "I have never burned a village",
  'And called the ashes "peace"',
  "",
  "I just killed him",
  "And I left",
  "",
  "And you hate me for that",
  "Not for the killing",
  "For the honesty",
  "",
  "Your Light says love",
  "While its armies march",
  "Your Fire says freedom",
  "While the forests choke",
  "Your Earth says patience",
  "While the hungry wait",
  "And wait",
  "And wait",
  "Until the waiting kills them quieter than any blade I own",
  "",
  "They sent their children to my streets",
  "The ones the temples wouldn't feed",
  "The ones the armies wouldn't take",
  "The ones the farmlands couldn't keep",
  "",
  "They came to me with empty hands",
  "I didn't give them prayers",
  "I gave them knives",
  "And they survived",
  "",
  "Is that not mercy?",
  "I'm asking",
  "",
  "When the Light wouldn't feed them",
  "And the Earth wouldn't hold them",
  "And the Fire wouldn't warm them",
  "",
  "I opened a door in the dark",
  'And said "come in, it\'s ugly in here, but it\'s warm"',
  '"and no one will lie to you"',
  "",
  "Is that not a kind of love?",
  "",
  "You'll never call it that",
  "I know",
  "",
  "You need me to be the villain",
  "So your story makes sense",
  "So your songs have a shadow to push against",
  "So your children know what darkness looks like",
  "And never notice it in the mirror",
  "",
  "That's fine",
  "I've been your monster long enough",
  "To know that monsters serve a purpose",
  "",
  "But sometimes",
  "Late at night",
  "When the treaties are signed",
  "And the prayers are said",
  "And the fires have cooled",
  "And the ground is still",
  "",
  "I wonder if any of you remember",
  "Who did the work",
  "That let you sleep",
  "",
  "So yes",
  "I live in the dark",
  "But I chose it",
  "Eyes open",
  "Hands dirty",
  "",
  "Heart - and you will never believe this -",
  "Honest",
  "",
  "The dark is not the absence of your light",
  "The dark was here first",
  "And it will be here last",
  "",
  "And it has never once",
  "Not once",
  "Pretended to be something",
  "It wasn't",
];

// ============================================================================
//  TRACK 4 - The Dawn Was Ours to Give (Light's Cathedral Anthem)
// ============================================================================
const DAWN_LYRICS: string[] = [
  "Before the fire",
  "Before the blade",
  "Before the shadow learned to trade",
  "There was a light",
  "And it was ours",
  "Not taken - given",
  "Not demanded - shared",
  "",
  "We opened our hands before the world had language",
  "And said here",
  "Here is warmth",
  "Here is sight",
  "Here is the name of every star",
  "",
  "We asked for nothing",
  "We have never asked for anything",
  "And still they turned away",
  "",
  "We built the hospitals",
  "We wrote the laws",
  "We buried the dead who cursed our name",
  "With the same hands that healed the living",
  "And we wept for both equally",
  "",
  "Do you understand",
  "We wept for both",
  "",
  "We did not come to your shores with chains",
  "We came with medicine",
  "We did not tear down your temples",
  "We opened our doors and let you see",
  "What worship looks like",
  "When it isn't afraid",
  "",
  "And you call that conquest",
  "You call that pride",
  "You look at the cathedral",
  "And see a cage",
  "",
  "But the door is open",
  "The door has always been open",
  "We would never lock it",
  "Why would we lock it",
  "Where would you go",
  "That isn't darker than where we brought you",
  "",
  "This is the part you will not hear",
  "This is the part that breaks my voice",
  "",
  "I did not want an empire",
  "I wanted a family",
  "I wanted to hold the broken thing",
  "And feel it heal beneath my hands",
  "And hear it say thank you",
  "",
  "Not because I needed the words",
  "But because the words would mean",
  "It understood",
  "That it was loved",
  "",
  "Is that so wrong",
  "To want the wounded world to know it's loved",
  "",
  "And if it will not know",
  "If it bites the hand",
  'If it calls the healer "tyrant"',
  'And the shelter "prison"',
  'And the hymn "a weapon"',
  "",
  "Then I will sing louder",
  "I will build the shelter stronger",
  "I will heal the hand that strikes me",
  "And I will not stop",
  "I will never stop",
  "",
  "Because stopping would mean",
  "The darkness was right",
  "And I cannot live in that world",
  "I am not built for that world",
  "",
  "You think my certainty is arrogance",
  "But you have never carried what I carry",
  "The weight of knowing what is good",
  "And watching the world choose otherwise",
  "Every single day",
  "",
  "And choosing to show up anyway",
  "With open hands",
  "With open doors",
  "With one more hymn",
  "One more dawn",
  "One more chance",
  "",
  "I will give you chances until I die",
  "And after I die",
  "The ones I taught will give you more",
  "",
  "Light is not a request",
  "Light is not a debate",
  "Light is the thing that happens to a room",
  "When someone strikes a match",
  "",
  "You can argue with the flame",
  "But the room is already brighter",
  "And you cannot un-see what was shown to you",
  "",
  "So hate us if you must",
  "Hate the warmth",
  "Hate the sight",
  "Hate the hand that reached for you",
  "When no one else would",
  "",
  "But know this",
  "And carry it with you into whatever dark you choose",
  "",
  "The dawn was ours to give",
  "We gave it freely",
  "And we will give it again tomorrow",
  "And the day after",
  "And the day after that",
  "",
  "Until the world is bright enough",
  "That it no longer needs us",
  "",
  "And on that day",
  "We will rest",
  "And we will be glad",
  "",
  "But not today",
  "Not today",
  "",
  "There is still so much dark",
  "And we have so much light to give",
];

// ============================================================================
//  TRACK 5 - The Ground Remembers (Earth's Anthem)
// ============================================================================
const GROUND_LYRICS: string[] = [
  "They ask me why I will not move",
  "As if moving were a virtue",
  "As if the river that abandons its bed",
  "Is braver than the stone that stays",
  "",
  "I have watched the river",
  "I have seen where it goes",
  "It goes everywhere",
  "It arrives nowhere",
  'And it calls this "freedom"',
  "",
  "I call it forgetting",
  "",
  "I do not forget",
  "",
  "There is a boy buried thirty steps from where I stand",
  "His name was Edric",
  "He was nine",
  "He could not lift his father's shield",
  "But he stood behind it when the fire came",
  "And the fire came",
  "",
  "And after the fire",
  "The light came",
  "With bandages and hymns",
  "And they healed the survivors",
  "And they built a school where his house had been",
  "And they taught his sisters new songs",
  "And within a year",
  "No one in the village could remember",
  "The song his mother used to sing",
  "",
  "Except the ground",
  "The ground remembers",
  "",
  "This is what none of them understand",
  "Not the shadow with its clever knives",
  "Not the light with its open hands",
  "Not the fire with its hungry mouth",
  "",
  "They think the world is something you do",
  "I know the world is something you hold",
  "",
  "You hold it the way you hold a child",
  "Who is too sick to stand",
  "You do not carry them toward something better",
  "You sit with them where they are",
  "And you do not leave",
  "",
  "That is not poetry",
  "That is Tuesday",
  "That is every day I have ever lived",
  "",
  "They call me stubborn",
  "They are right",
  "They say it like it is a flaw",
  "Like the mountain should apologize",
  "For being in the way",
  "",
  "I am in the way",
  "I have always been in the way",
  "I will be in the way long after",
  "The armies have rusted",
  "And the treaties have yellowed",
  "And the gods have been forgotten",
  "By the people who made them",
  "",
  "I did not make gods",
  "I made walls",
  "I made roots",
  "I made graves that stay where you put them",
  "",
  "And yes",
  "They are graves",
  "I know what I am standing on",
  "I have always known",
  "",
  "You think I hold this ground because I love it",
  "You are half right",
  "I hold this ground because it holds my dead",
  "And I will not walk away from my dead",
  "For your progress",
  "For your freedom",
  "For your dawn",
  "For your revolution",
  "",
  "You can offer me the whole horizon",
  "I will take this field",
  "",
  "Because this field has a name",
  "And the name is every person",
  "Who trusted me enough to die here",
  "",
  "Do you understand what land is",
  "Not territory",
  "Not resource",
  "Not strategic position",
  "",
  "Land is a promise",
  "That someone will remember where you fell",
  "",
  "And I am the promise",
  "",
  "I am the one who remembers",
  "When the fire has moved on to the next burning",
  "When the light has moved on to the next saving",
  "When the shadow has moved on to the next scheme",
  "",
  "I am still here",
  "In the same field",
  "With the same hands",
  "Saying the same names",
  "Every morning",
  "",
  "Edric",
  "Maren",
  "Tobas",
  "Yreth",
  "Clay",
  "",
  "I say them so the wind carries them",
  "I say them so the ground knows",
  "It has not been abandoned",
  "",
  "They tell me the world is changing",
  "I know",
  "I have watched it change",
  "Nine hundred times",
  "It always changes back",
  "",
  "The names are different",
  "The fire is the same",
  "The light is the same",
  "The shadow is the same",
  "",
  "Only the ground is different",
  "Because the ground gains",
  "One more name",
  "Every time",
  "",
  "And I hold them all",
  "",
  "You want to know why I will not move",
  "Why I build the wall higher instead of building a road out",
  "Why I teach my children to stand instead of to run",
  "Why I plant trees that I will never sit beneath",
  "",
  "Because someone has to be the place",
  "That does not move",
  "When everything else does",
  "",
  "Someone has to be the ground",
  "That the fleeing child runs toward",
  "Not because it is safe",
  "Nothing is safe",
  "But because it is there",
  "When nothing else is",
  "",
  "I am not brave",
  "I am not wise",
  "I am not kind",
  "",
  "I am present",
  "",
  "And in a world that burns and heals and steals and forgets",
  "",
  "Present",
  "Is the most radical thing",
  "A person can be",
  "",
  "So I will stand here",
  "Where Edric fell",
  "Where Maren planted the oak that shades his stone",
  "Where Tobas built the wall that held for thirty years",
  "Where Yreth sang the song the light tried to replace",
  "Where Clay - small, quiet Clay -",
  "Died with dirt in his hands",
  "Because he was planting when the soldiers came",
  "And he did not stop planting",
  "",
  "He did not stop",
  "",
  "And neither will I",
  "",
  "The ground remembers what the world does not",
  "That someone stood here",
  "That someone stayed",
  "That someone chose the field over the horizon",
  "And called it enough",
  "",
  "And it was",
  "",
  "It was enough",
];

// ============================================================================
//  TRACK 6 - I Burned First (Fire's Anthem)
// ============================================================================
const BURNED_FIRST_LYRICS: string[] = [
  "I want you to know",
  "Before the heat comes",
  "Before the air turns",
  "Before you see me as the monster",
  "In the story you'll tell your children",
  "",
  "I want you to know",
  "That I can see you",
  "That I know what this is",
  "That I know what you built here",
  "And it is beautiful",
  "",
  "The stone you carried from the river",
  "The door your father hung",
  "The garden where your daughter learned the word for rain",
  "I see it",
  "I have always seen it",
  "",
  "I am not blind",
  "That is my punishment",
  "I see everything I burn",
  "",
  "Do you think I came here hungry",
  "Do you think I woke this morning",
  "And chose destruction like a garment",
  "Put on fury like a coat",
  "",
  "I woke this morning",
  "And I held my hands over the cookfire",
  "And I watched the flames",
  "And I said",
  "Not today",
  "Please",
  "Not today",
  "",
  "But the fields to the south are choking",
  "And the river has not moved in seven years",
  "And your walls - your beautiful walls -",
  "Have kept the rot inside as much as they kept the danger out",
  "And the children in the eastern quarter",
  "Have not seen sunlight",
  "Because the canopy your ancestors planted with such love",
  "Has grown so thick",
  "That love itself has become the ceiling",
  "That holds them down",
  "",
  "And no one will cut it",
  "Because it was planted with love",
  "And who burns a thing that was planted with love",
  "",
  "I do",
  "God help me",
  "I do",
  "",
  "Not because I hate the tree",
  "But because I love the children",
  "More than I love the tree",
  "And you will never forgive me for that arithmetic",
  "",
  "This is what they will never write about us",
  "In the histories",
  "In the songs",
  "In the accounts of who did what to whom",
  "",
  "They will write that fire came",
  "They will not write that fire wept",
  "",
  "They will write that the city burned",
  "They will not write the hour I stood at the gates",
  "Arguing with myself",
  "Begging myself",
  "To find another way",
  "",
  "There is no other way",
  "I have looked",
  "I have spent lifetimes looking",
  "Light tried to heal the rot and the rot healed around the medicine",
  "Earth tried to hold the rot in place and the rot became the foundation",
  "Shadow tried to cut the rot out in the dark and the rot grew back twice as thick",
  "",
  "The only thing that kills rot",
  "Is heat",
  "The only thing that clears the canopy",
  "Is flame",
  'The only thing honest enough to say',
  '"This must go so that something can come"',
  "Is fire",
  "",
  "And I wish it weren't me",
  "I wish there were another element",
  "Between mercy and destruction",
  "A gentle fire",
  "A kind blaze",
  "A flame that burns only the parts that need burning",
  "And leaves the rest untouched",
  "",
  "But fire does not negotiate",
  "Fire does not do surgery",
  "Fire is the blunt and total answer",
  "To the question no one else will ask",
  "",
  "And the question is",
  "What do you love enough to destroy",
  "",
  "I love the future more than the past",
  "That is my confession",
  "That is the sin I will carry",
  "Into every field I clear",
  "Every forest I open",
  "Every city I unmake so the next city can breathe",
  "",
  "I love what comes after",
  "More than what came before",
  "",
  "And I have never asked anyone to forgive me for that",
  "Because forgiveness requires understanding",
  "And no one understands",
  "Until they have stood in the ash",
  "And watched the first green thing",
  "Push through",
  "",
  "I have seen it",
  "A thousand times",
  "The shoot",
  "Pale and impossible",
  "Rising from black ground",
  "",
  "And it is the most beautiful thing in the world",
  "More beautiful than the forest was",
  "Because the forest was given",
  "And the shoot is chosen",
  "The shoot chooses to grow",
  "In the place where everything was taken",
  "",
  "That is not destruction",
  "That is faith",
  "",
  "The most radical faith there is",
  "Faith that the world wants to live",
  "That life will find the clearing",
  "That the seed was waiting",
  "All along",
  "For someone brave enough",
  "Or cursed enough",
  "To make room",
  "",
  "I make room",
  "That is all I do",
  "I make room",
  "",
  "And they call it destruction",
  "And they are not wrong",
  "And I call it love",
  "And I am not wrong either",
  "",
  "And that is the war",
  "Not sword against shield",
  "Not shadow against light",
  "The war is two truths",
  "That cannot live in the same room",
  "And I am always the one",
  "Who burns the room down",
  "So we can find out",
  "Which truth survives in open air",
  "",
  "Before I came to your gates",
  "I burned my own house",
  "Did they tell you that",
  "I burned my garden first",
  "My door first",
  "My father's chair",
  "My daughter's drawing of the sun",
  "",
  "Because I will not ask you to lose",
  "What I have not already lost",
  "I will not burn your world",
  "From the safety of mine",
  "",
  "My hands were ash",
  "Before they ever touched your walls",
  "",
  "That is the pact",
  "That is the Emberheart",
  "We burn first",
  "Always first",
  "Ourselves before others",
  "Our homes before yours",
  "Our grief before your grief",
  "",
  "And when there is nothing left of us",
  "We burn the air itself",
  "And call it breathing",
  "",
  "So before the heat comes",
  "Before you teach your children what I am",
  "Before you write the history",
  "",
  "Remember this",
  "",
  "I saw your garden",
  "I knew the word your daughter learned for rain",
  "I wept for the door your father hung",
  "",
  "And I burned it all",
  "",
  "Because forty years from now",
  "Your granddaughter will stand in a field",
  "That is only a field",
  "Because I cleared it",
  "And she will not know my name",
  "And she will plant something",
  "And it will grow",
  "And it will grow",
  "And it will grow",
  "",
  "And that",
  "Is why I can live with what I am",
  "",
  "I burned first",
  "I burned myself first",
  "And I would do it again",
  "",
  "Not because it doesn't hurt",
  "",
  "Because it does",
  "",
  "Always",
];

// ============================================================================
//  PLAYLIST
// ============================================================================
export const BATTLE_TRACKS: Track[] = [
  {
    id: "ashes-remember",
    title: "Ashes Remember",
    artist: "The Shattered Dominion",
    src: ashesRememberSrc,
    lyrics: ASHES_REMEMBER_LYRICS,
  },
  {
    id: "every-kingdom-believes",
    title: "Every Kingdom Believes",
    artist: "The Shattered Dominion",
    src: everyKingdomSrc,
    lyrics: EVERY_KINGDOM_LYRICS,
  },
  {
    id: "the-honest-dark",
    title: "The Honest Dark",
    artist: "Obsidian Veil - Shadow's Anthem",
    src: theHonestDarkSrc,
    lyrics: HONEST_DARK_LYRICS,
  },
  {
    id: "the-dawn-was-ours-to-give",
    title: "The Dawn Was Ours to Give",
    artist: "Radiant Sovereignty - Light's Anthem",
    src: theDawnSrc,
    lyrics: DAWN_LYRICS,
  },
  {
    id: "the-ground-remembers",
    title: "The Ground Remembers",
    artist: "Ironbark Bastion - Earth's Anthem",
    src: theGroundSrc,
    lyrics: GROUND_LYRICS,
  },
  {
    id: "i-burned-first",
    title: "I Burned First",
    artist: "Emberheart Pact - Fire's Anthem",
    src: iBurnedFirstSrc,
    lyrics: BURNED_FIRST_LYRICS,
  },
];
